apiVersion: v1
kind: ConfigMap
metadata:
  name: kanboard-ldap-configuration
data:
  LDAP_AUTH: "false"
  LDAP_SERVER: ""
  LDAP_PORT: "389"
  LDAP_SSL_VERIFY: "true"
  LDAP_START_TLS: "false"
  LDAP_USERNAME_CASE_SENSITIVE: "false"
  LDAP_BIND_TYPE: "anonymous"
  LDAP_USER_BASE_DN: ""
  LDAP_USER_FILTER: ""
  LDAP_GROUP_USER_ATTRIBUTE: "dn"
  LDAP_USER_ATTRIBUTE_USERNAME: "uid"
  LDAP_USER_ATTRIBUTE_FULLNAME: "cn"
  LDAP_USER_ATTRIBUTE_EMAIL: "mail"
  LDAP_USER_ATTRIBUTE_GROUPS: "memberof"
  LDAP_USER_ATTRIBUTE_PHOTO: ""
  LDAP_USER_ATTRIBUTE_LANGUAGE: ""
  LDAP_USER_CREATION: "true"
  LDAP_USER_DEFAULT_ROLE_MANAGER: "false"
  LDAP_GROUP_ADMIN_DN: ""
  LDAP_GROUP_MANAGER_DN: ""
  LDAP_GROUP_PROVIDER: "false"
  LDAP_GROUP_BASE_DN: ""
  LDAP_GROUP_FILTER: ""
  LDAP_GROUP_USER_FILTER: ""
  LDAP_GROUP_ATTRIBUTE_NAME_: "cn"