apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanboard
spec:
  selector:
    matchLabels:
      app: kanboard
  template:
    metadata:
      labels:
        app: kanboard
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kanboard-data
        - name: plugins
          persistentVolumeClaim:
            claimName: kanboard-plugins
      containers:
      - name: kanboard
        image: 	ghcr.io/kanboard/kanboard:v1.2.26 
        envFrom:
          - configMapRef:
              name: kanboard-bruteforce-protection
          - configMapRef:
              name: kanboard-cache-parameters
          - configMapRef:
              name: kanboard-database-configuration
          - secretRef:
              name: kanboard-database-configuration-secret
          - secretRef:
              name: kanboard-email-configuration-secret
          - configMapRef:
              name: kanboard-email-configuration
          - secretRef:
              name: kanboard-http-client-secret
          - configMapRef:
              name: kanboard-http-client
          - secretRef:
              name: kanboard-ldap-configuration-secret
          - configMapRef:
              name: kanboard-ldap-configuration
          - configMapRef:
              name: kanboard-logging
          - configMapRef:
              name: kanboard-miscellaneous
          - configMapRef:
              name: kanboard-plugins
          - configMapRef:
              name: kanboard-rememberme
          - configMapRef:
              name: kanboard-reverse-proxy-configuration
          - configMapRef:
              name: kanboard-secure-http-headers
          - configMapRef:
              name: kanboard-session
          - configMapRef:
              name: kanboard-uploaded-files
          - configMapRef:
              name: kanboard-url-rewrite
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/app/data
            name: data
          - mountPath: /var/www/app/plugins
            name: plugins
